name: build
version: v1.0
stages:
  - stage: build
    jobs:
      - job: compile
        steps:
          - script:
              name: Compile
              script: |
                echo "Building project..."
